repos:
-   repo: local
    hooks:
    - id: black
      name: black
      language: system
      entry: black --config django/pyproject.toml
      types: [python]
      exclude: >
          (?x)^(
            .*/migrations/.* |
            .*/snapshots/.*
          )$
    - id: isort
      name: isort
      language: system
      entry: isort
      types: [python]
    - id: flake8
      name: flake8
      language: system
      entry: flake8 --config django/.flake8
      types: [python]
