search: False
requirements:
        - django/requirements.txt:
                update: all
                pin: True
        - django/requirements-dev.txt:
                update: all
                pin: True
