version: "3.4"
services:
    proxy:
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/camac/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/camac/letsencrypt:/var/www/letsencrypt:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem:ro

    db:
        image: acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}
        restart: always
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
        volumes:
            - /etc/camac/postgres_password.conf:/run/secrets/postgres-passwd:ro

    django:
        image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}
        restart: always
        environment:
            - DJANGO_ENV_FILE=/run/secrets/django.env
        volumes:
            - /etc/camac/django.env:/run/secrets/django.env:ro

    ember:
        image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}
        restart: always

    php:
        image: acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}
        restart: always
        environment:
            - APPLICATION_ENV=production-${APPLICATION}
            - APPLICATION=${APPLICATION}
        volumes:
            - /etc/camac/application.ini:/var/www/camac/application/configs/application.local.ini

    cache:
        restart: always

    unoconv:
        restart: always

    clamav:
        restart: always

    keycloak:
        # disable keycloak
        # workaround for https://github.com/docker/compose/issues/1896
        command: /bin/true

volumes:
    pgdata:
        external:
            name: camacpgdata

    djangomedia:
        external:
            name: camacdjangomedia
