version: "3.4"
services:
    camac-django:
        image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}
        build:
            context: django
            cache_from:
                - acr.run/camac-ng/camac-ng/django:master

    camac-ember:
        image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}
        build:
            context: ember
            cache_from:
                - acr.run/camac-ng/camac-ng/ember:master
