version: "3.4"
services:
    db:
        image: acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/db:master
        environment:
            - POSTGRES_PASSWORD=camac

    django:
        image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/django:master
        environment:
            - DJANGO_KEYCLOAK_URL=http://keycloak:8080/auth/

    ember:
        image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/ember:master

    php:
        image: acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/php:master

    keycloak:
        volumes:
            - ./keycloak:/etc/keycloak:ro
        environment:
            - POSTGRES_PASSWORD=camac
            - KEYCLOAK_PASSWORD=camac
