version: "3.4"
services:
    cache:
        image: memcached:1.5-alpine

    proxy:
        image: nginx:1.13-alpine
        depends_on:
            - ember
            - php
            - django
            - keycloak

    db:
        build:
            context: db
        environment:
            - POSTGRES_USER=camac
            - POSTGRES_DATABASE=${APPLICATION}
        volumes:
            - pgdata:/var/lib/postgresql/data

    django:
        build:
            context: django
        depends_on:
            - db
            - cache
            - clamav
            - keycloak
        environment:
            - DJANGO_DATABASE_HOST=db
            - DJANGO_DATABASE_NAME=${APPLICATION}
            - DJANGO_CACHE_LOCATION=cache:11211
            # TODO: nginx should serve media files
            - DJANGO_MEDIA_ROOT=/var/lib/camac/media
            - DJANGO_UNOCONV_URL=http://unoconv:3000
            - DJANGO_CLAMD_TCP_ADDR=clamav
        volumes:
            - djangomedia:/var/lib/camac/media

    ember:
        build:
            context: ember
        depends_on:
            - django
        environment:
            - ENV=docker

    php:
        build:
            context: php
        depends_on:
            - db
            - django
            - cache
            - keycloak

    unoconv:
        image: zrrrzzt/docker-unoconv-webservice:8.9.4

    clamav:
        image: dinkel/clamavd

    keycloak:
        depends_on:
            - db
        image: jboss/keycloak:3.4.3.Final
        volumes:
            - ./keycloak:/etc/keycloak:ro
        environment:
            - POSTGRES_PORT_5432_TCP_ADDR=db
            - POSTGRES_USER=camac
            - POSTGRES_DATABASE=${APPLICATION}
            - KEYCLOAK_USER=admin
        # http://www.keycloak.org/docs/3.3/server_admin/topics/export-import.html
        command: ["-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/etc/keycloak/test-config.json", "-b", "0.0.0.0"]

volumes:
    pgdata:
    djangomedia:
