version: "3.4"
services:
    cache:
        image: memcached:1.5-alpine

    proxy:
        image: nginx:1.13-alpine
        depends_on:
            - caluma
            - ember
            - php
            - django
            - keycloak
            - mailcatcher
        volumes:
            - djangomedia:/var/lib/camac/media:ro

    db:
        build:
            context: db
            cache_from:
                - acr.run/camac-ng/camac-ng/db:master
        environment:
            - POSTGRES_USER=camac
            - POSTGRES_DATABASE=${APPLICATION}
        volumes:
            - pgdata:/var/lib/postgresql/data

    caluma:
      restart: always
      build:
        context: caluma
        cache_from:
          - acr.run/camac-ng/camac-ng/caluma:master
      environment:
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_NAME=caluma
        - DATABASE_PASSWORD=camac
        - DATABASE_USER=camac
        - ENV=development
      depends_on:
        - php
        - db

    django:
        build:
            context: django
            cache_from:
                - acr.run/camac-ng/camac-ng/django:master
        depends_on:
            - db
            - cache
            - clamav
            - keycloak
            - mailcatcher
        environment:
            - DJANGO_DATABASE_HOST=db
            - DJANGO_DATABASE_NAME=${APPLICATION}
            - DJANGO_CACHE_LOCATION=cache:11211
            - DJANGO_MEDIA_ROOT=/var/lib/camac/media
            - DJANGO_UNOCONV_URL=http://unoconv:3000
            - DJANGO_CLAMD_TCP_ADDR=clamav
            - APPLICATION=${APPLICATION}
        volumes:
            - djangomedia:/var/lib/camac/media

    ember:
        build:
            context: ember
            cache_from:
                - acr.run/camac-ng/camac-ng/ember:master
        depends_on:
            - django
        environment:
            - ENV=docker

    php:
        build:
            context: php
            cache_from:
                - acr.run/camac-ng/camac-ng/php:master
        depends_on:
            - db
            - django
            - cache
            - keycloak
            - mailcatcher
        environment:
            - APPLICATION=${APPLICATION}
        volumes:
            - djangomedia:/var/www/camac/media
            - phpsessions:/var/www/camac/sessions
            - /var/www/camac/vendor
            - /var/www/camac/public/public-kt_bern/css
            - /var/www/camac/public/public-kt_bern/js
            - /var/www/camac/public/node_modules
            - /var/www/camac/public/bower_components

    mailcatcher:
        image: schickling/mailcatcher

    unoconv:
        image: zrrrzzt/docker-unoconv-webservice:8.9.4

    clamav:
        image: dinkel/clamavd

    keycloak:
        depends_on:
            - db
        image: acr.run/camac-ng/keycloak:3.4.3.Final_theme-v0.2.0-SNAPSHOT
        environment:
            - POSTGRES_PORT_5432_TCP_ADDR=db
            - POSTGRES_USER=camac
            - POSTGRES_DATABASE=${APPLICATION}
            - KEYCLOAK_USER=admin

    postfix:
        image: tozd/postfix

        environment:
            - MY_NETWORKS=172.16.0.0/12 127.0.0.0/8
        volumes:
            - postfixdata:/var/spool/postfix

volumes:
    pgdata:
    djangomedia:
    phpsessions:
    postfixdata:
