version: "3.4"
services:
    db:
        image: acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/db:master
        environment:
            - POSTGRES_PASSWORD=camac

    django:
        image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/django:master

    ember:
        image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/ember:master

    php:
        image: acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}
        build:
            cache_from:
                - acr.run/camac-ng/camac-ng/php:master
