version: "3.4"
services:
    cache:
        image: memcached:1.5-alpine

    proxy:
        image: nginx:1.13-alpine
        depends_on:
            - ember
            - php
            - django

    db:
        environment:
            - POSTGRES_USER=camac
            - POSTGRES_DATABASE=${APPLICATION}
        volumes:
            - camacpgdata:/var/lib/postgresql/data

    django:
        depends_on:
            - db
            - cache
        environment:
            - DJANGO_DATABASE_HOST=db
            - DJANGO_DATABASE_NAME=${APPLICATION}
            - DJANGO_CACHE_LOCATION=cache:11211
            # TODO: nginx should serve media files
            - DJANGO_MEDIA_ROOT=/var/lib/camac/media
            - DJANGO_UNOCONV_URL=http://unoconv:3000
        volumes:
            - camacdjangomedia:/var/lib/camac/media

    ember:
        depends_on:
            - django
        environment:
            - ENV=docker

    php:
        depends_on:
            - db
            - django
            - cache

    unoconv:
        image: zrrrzzt/docker-unoconv-webservice:8.9.4
        ports:
            - '3000:3000'

volumes:
    camacpgdata:
    camacdjangomedia:
