version: "3.4"
services:
    cache:
        image: memcached:1.5-alpine

    db:
        image: postgres:9.5-alpine
        environment:
            - POSTGRES_USER=camac
            - POSTGRES_DATABASE=${APPLICATION}
        volumes:
            - camacpgdata:/var/lib/postgresql/data
            - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro

    proxy:
        image: nginx:1.13-alpine
        depends_on:
            - ember
            - php
            - django

    django:
        depends_on:
            - db
            - cache
        environment:
            - DJANGO_DATABASE_HOST=db
            - DJANGO_DATABASE_NAME=${APPLICATION}
            - DJANGO_CACHE_LOCATION=cache:11211
            # TODO: nginx should serve media files
            - DJANGO_MEDIA_ROOT=/var/lib/camac/media
        volumes:
            - camacdjangomedia:/var/lib/camac/media

    ember:
        depends_on:
            - django
        environment:
            - ENV=docker

    php:
        depends_on:
            - db
            - django
            - cache

volumes:
    camacpgdata:
        external: true
    camacdjangomedia:
        external: true
