version: "2"
services:
    camac-cache:
        image: memcached

    camac-db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=camac
            - POSTGRES_USER=camac
            - POSTGRES_DB=camac

    camac-django:
        depends_on:
          - camac-db
          - camac-cache
        environment:
          - ENV=docker
          - DJANGO_DATABASE_HOST=camac-db
          - DJANGO_CACHE_LOCATION=camac-cache:11211

    camac-ember:
        depends_on:
            - camac-django
        environment:
          - ENV=docker
