version: "3.4"
services:
    proxy:
        image: nginx:1.13-alpine
        depends_on:
            - caluma
            - ember
            - php
            - django
            - keycloak
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /etc/camac/nginx:/etc/nginx/conf.d:ro
            - djangomedia:/var/lib/camac/media:ro

    django:
        image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
        build:
            context: django
            cache_from:
                - acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
        depends_on:
            - cache
            - clamav
            - keycloak
        restart: always
        environment:
            - DJANGO_ENV_FILE=/run/secrets/django.env
        volumes:
            - /etc/camac/django.env:/run/secrets/django.env:ro

    ember:
        image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
        build:
            context: ember
            cache_from:
                - acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
        depends_on:
            - django
        restart: always
        build:
            args:
                KEYCLOAK_URL_ARG: ${KEYCLOAK_URL}

    php:
        image: acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}-${APPLICATION}
        build:
            context: php
            cache_from:
                - acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}-${APPLICATION}
        depends_on:
            - django
            - cache
            - keycloak
        restart: always
        environment:
            - APPLICATION_ENV=production
        volumes:
            - /etc/camac/php.ini:/usr/local/etc/php/php.ini:ro
            - /etc/camac/application.ini:/var/www/camac/${APPLICATION}/configs/application.local.ini:ro
            # TODO: Implement resource fallback in document module, so this can be removed
            - phpresources:/var/www/camac/kt_uri/resources

    cache:
        image: memcached:1.5-alpine
        restart: always

    unoconv:
        image: zrrrzzt/docker-unoconv-webservice:8.9.4
        restart: always

    clamav:
        image: dinkel/clamavd
        restart: always

    keycloak:
        image: acr.run/camac-ng/keycloak:3.4.3.Final_theme-v0.2.0-SNAPSHOT
        volumes:
            - /etc/camac/keycloak.env:/run/secrets/keycloak.env:ro
        environment:
            - ENV_FILE=/run/secrets/keycloak.env
        restart: always

volumes:
    djangomedia:
        external:
            name: camacdjangomedia

    phpsessions:
        external:
            name: camacphpsessions

    phpresources:
        external:
            name: camacphpresources
