version: "3.4"
services:
    cache:
        image: memcached:1.5-alpine

    db:
        image: postgres:9.5-alpine
        environment:
            - POSTGRES_PASSWORD=camac
            - POSTGRES_USER=camac
            - POSTGRES_DB=camac

    django:
        depends_on:
            - db
            - cache
        environment:
            - ENV=docker
            - DJANGO_DATABASE_HOST=db
            - DJANGO_CACHE_LOCATION=cache:11211

    ember:
        depends_on:
            - django
        environment:
            - ENV=docker

    php:
        depends_on:
            - db
            - django
            - cache
