version: "3.4"
services:
    cache:
        ports:
            - "11211:11211"
        networks:
            - camac-ng.local

    proxy:
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
        depends_on:
            - iweb_mock
        networks:
            camac-ng.local:
                aliases:
                    - camac-ng.local
                    - camac-ng-portal.local
                    - camac-ng-keycloak.local

    clamav:
        ports:
            - "3310:3310"
        networks:
            - camac-ng.local

    db:
        # Workaround, same name of image as cache_from
        # better be named differently once following is fixed:
        # https://github.com/docker/compose/issues/5458
        # see also other services below
        image: acr.run/camac-ng/camac-ng/db:master
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=camac
        volumes:
            - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
        networks:
            - camac-ng.local

    django:
        image: acr.run/camac-ng/camac-ng/django:master
        volumes:
            - ./django:/app
        environment:
            - APPLICATION_ENV=development
            - KEYCLOAK_URL=http://keycloak:8080/auth/
            - DJANGO_EMAIL_HOST=mailcatcher
            - DJANGO_EMAIL_PORT=1025
        networks:
            - camac-ng.local
        command: /bin/sh -c "./wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py loadconfig && ./manage.py runserver 0.0.0.0:80"

    ember:
        image: acr.run/camac-ng/camac-ng/ember:master
        volumes:
            - ./ember/nginx.conf:/etc/nginx/sites-enabled/default:ro
            - ./ember:/app
            - /app/node_modules/
            - /app/tmp/
            - /app/dist/
            - /app/build/
        networks:
            - camac-ng.local
        build:
            args:
                KEYCLOAK_URL_ARG: http://camac-ng-keycloak.local/auth/

    php:
        image: acr.run/camac-ng/camac-ng/php:master
        volumes:
            - ./php/php.ini-development:/usr/local/etc/php/php.ini:ro
            - ./php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
            - ./php:/var/www/camac
            - /var/www/camac/vendor
            - /var/www/camac/configuration
            - /var/www/camac/public/node_modules
            - /var/www/camac/public/public-kt_uri/js/dist
            - /var/www/camac/public/public-kt_schwyz/js/dist
        environment:
            - APPLICATION_ENV=development
        networks:
            - camac-ng.local
        command: ["/bin/sh", "-c", "chown -R www-data:www-data /var/www/camac/media /var/www/camac/sessions && rm -f configuration/* && cd configuration && ln -sf ../${APPLICATION}/* . && php -d xdebug.remote_enable=off /var/www/camac/cronjob/clear-cache.php && apache2-foreground"]

    unoconv:
        ports:
            - '3000:3000'
        networks:
            - camac-ng.local

    keycloak:
        ports:
            - '8080:8080'
        volumes:
            - ./keycloak:/etc/keycloak:ro
        environment:
            - POSTGRES_PASSWORD=camac
            - KEYCLOAK_PASSWORD=camac
        networks:
            - camac-ng.local
        # http://www.keycloak.org/docs/3.3/server_admin/topics/export-import.html
        command: ["-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/etc/keycloak/test-config.json", "-b", "0.0.0.0"]

    mailcatcher:
        ports:
            - '1080:1080'
        networks:
            - camac-ng.local

    iweb_mock:
        image: node:6
        volumes:
            - ./iweb_mock:/usr/src/app
        command: bash /usr/src/app/run_mock
        environment:
            - NODE_ENV=development
        depends_on:
            - php
        networks:
            - camac-ng.local


networks:
    camac-ng.local:
