version: "3.4"
services:
  proxy:
    image: nginx:1.21-alpine
    depends_on:
      - ember
      - ember-camac-ng
      - django
      - keycloak
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/certbot:/etc/certbot:ro
      - /srv/www/htdocs:/var/www/letsencrypt:ro
      - /etc/camac/nginx:/etc/nginx/conf.d:ro
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro

  django: &django
    image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    depends_on:
      - cache
      - clamav
      - keycloak
      - unoconv
      - postfix
    restart: always
    environment:
      - DATABASE_HOST=vm-kantonsz-db-vip.cust.adfinis-sygroup.ch
      - DJANGO_ENV_FILE=/run/secrets/django.env
      - DJANGO_MERGE_DATE_FORMAT=%-d. %B %Y
    volumes:
      - /etc/camac/django.env:/run/secrets/django.env:ro
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles

  django-q:
    <<: *django
    command: /bin/sh -c "./wait-for-it.sh db:5431 -- ./manage.py qcluster --pythonpath /app/$APPLICATION"

  ember:
    image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
      args:
        KEYCLOAK_URL_ARG: ${KEYCLOAK_URL}
        DEPLOY_TARGET: production
    depends_on:
      - django
    restart: always

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
      args:
        - APPLICATION=${APPLICATION}
    restart: always

  cache:
    image: memcached:1.6-alpine
    restart: always

  unoconv:
    image: zrrrzzt/docker-unoconv-webservice:8.9.4
    restart: always

  clamav:
    image: tiredofit/clamav:2.3.0
    environment:
      - CONCURRENT_DATABASE_RELOAD=false
      - DEFINITIONS_UPDATE_FREQUENCY=1440
      - DEFINITIONS_UPDATE_BEGIN=0300
    restart: always

  keycloak:
    image: acr.run/camac-ng/keycloak:16.1.0_theme-v1.0.1
    volumes:
      - /etc/camac/keycloak.env:/run/secrets/keycloak.env:ro
    environment:
      - ENV_FILE=/run/secrets/keycloak.env
    restart: always

  postfix:
    image: mwader/postfix-relay
    restart: always
    environment:
      - POSTFIX_myhostname=ebau-sz.ch
      - POSTFIX_mail_name=noreply@ebau-sz.ch

  metabase:
    image: metabase/metabase:v0.43.2
    ports:
      - "666:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=${METABASE_DB_PASS_PROD}
      - MB_DB_HOST=vm-kantonsz-db-vip.cust.adfinis-sygroup.ch
    restart: always

volumes:
  djangomedia:
    external:
      name: camacdjangomedia

  djangotmpmedia:
    external:
      name: camacdjangotmpmedia

  phpsessions:
    external:
      name: camacphpsessions

  phpresources:
    external:
      name: camacphpresources
