version: "3.4"
services:
  proxy:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mailhog
      - postfix
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/camac/nginx:/etc/nginx/conf.d:ro

  db:
    image: acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    volumes:
      - /etc/camac/postgres_password.conf:/run/secrets/postgres-passwd:ro

  django: &django
    image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    depends_on:
      - postfix
      - mailhog
    environment:
      - DATABASE_NAME=kt_schwyz_dist
      - DJANGO_ENV_FILE=/run/secrets/django.env
    volumes:
      - /etc/camac/django.env:/run/secrets/django.env:ro

  django-q:
    <<: *django
    environment:
      - DJANGO_ENV_FILE=/run/secrets/django.env
    volumes:
      - /etc/camac/django.env:/run/secrets/django.env:ro

  ember:
    image: acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../ember
      cache_from:
        - acr.run/camac-ng/camac-ng/ember:${CI_COMMIT_REF_SLUG}-${APPLICATION}
      args:
        KEYCLOAK_URL_ARG: ${KEYCLOAK_URL}
        INTERNAL_HOST_ARG: ${INTERNAL_HOST}
        DEPLOY_TARGET: staging
    restart: always

  ember-camac-ng:
    image: acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../
      dockerfile: ./ember-camac-ng/Dockerfile
      cache_from:
        - acr.run/camac-ng/camac-ng/ember-camac-ng:${CI_COMMIT_REF_SLUG}-${APPLICATION}
      args:
        - APPLICATION=${APPLICATION}
    restart: always

  cache:
    restart: always

  unoconv:
    restart: always

  clamav:
    restart: always

  keycloak:
    volumes:
      - /etc/camac/keycloak.env:/run/secrets/keycloak.env:ro
    environment:
      - ENV_FILE=/run/secrets/keycloak.env
    restart: always

  postfix:
    image: mwader/postfix-relay
    restart: always
    environment:
      - POSTFIX_myhostname=camac-schwyz.sycloud.ch
      - POSTFIX_mail_name=noreply@camac-schwyz.sycloud.ch

  mailhog:
    image: mailhog/mailhog
    restart: always
    environment:
      - MH_UI_WEB_PATH=mailhog

  metabase:
    environment:
      - MB_DB_PASS=${METABASE_DB_PASS_STAGE}
    restart: always

volumes:
  pgdata:
    external:
      name: camacpgdata

  djangomedia:
    external:
      name: camacdjangomedia

  phpsessions:
    external:
      name: camacphpsessions

  phpresources:
    external:
      name: camacphpresources
