version: "3.4"
services:
  cache:
    image: memcached:1.5-alpine

  proxy:
    image: nginx:1.13-alpine
    depends_on:
      - php
      - django
      - keycloak
      - mailhog
    volumes:
      - djangomedia:/var/lib/camac/media:ro
      - djangotmpmedia:/tmp/camac/tmpfiles:ro

  db:
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:master
    environment:
      - POSTGRES_USER=camac
      - POSTGRES_DATABASE=${APPLICATION}
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:master
    depends_on:
      - db
      - keycloak
      - cache
      - clamav
      - mailhog
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${APPLICATION}
      - DJANGO_CACHE_LOCATION=cache:11211
      - DJANGO_MEDIA_ROOT=/var/lib/camac/media
      - DJANGO_CLAMD_TCP_ADDR=clamav
      - APPLICATION=${APPLICATION}
      - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
      - CACHE_LOCATION=cache:11211
      - EVENT_RECEIVER_MODULES=camac.caluma.extensions.events
      - VISIBILITY_CLASSES=camac.caluma.extensions.visibilities.CustomVisibility
      - PERMISSION_CLASSES=camac.caluma.extensions.permissions.CustomPermission
      - VALIDATION_CLASSES=camac.caluma.extensions.validations.CustomValidation
      - DATA_SOURCE_CLASSES=camac.caluma.extensions.data_sources.Municipalities,camac.caluma.extensions.data_sources.Services
      - DYNAMIC_GROUPS_CLASSES=camac.caluma.extensions.dynamic_groups.CustomDynamicGroups
      - DYNAMIC_TASKS_CLASSES=camac.caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - OIDC_USERNAME_CLAIM=preferred_username
      - OIDC_BOOTSTRAP_BY_EMAIL_FALLBACK=true
      - URI_MIGRATE_PORTAL_USER=true
      - META_FIELDS=camac-instance-id,ebau-number,submit-date
      - ENABLE_HISTORICAL_API=true
      - KEYCLOAK_REALM=urec
    volumes:
      - djangomedia:/var/lib/camac/media
      - djangotmpmedia:/tmp/camac/tmpfiles

  php:
    build:
      context: ../php
      cache_from:
        - acr.run/camac-ng/camac-ng/php:master
    depends_on:
      - db
      - keycloak
      - django
      - cache
      - mailhog
    environment:
      - APPLICATION=${APPLICATION}
    volumes:
      - djangomedia:/var/www/camac/media
      - phpsessions:/var/www/camac/sessions
      - /var/www/camac/vendor
      - /var/www/camac/public/public-kt_bern/css
      - /var/www/camac/public/public-kt_bern/js
      - /var/www/camac/public/node_modules
      - /var/www/camac/public/bower_components

  mailhog:
    image: mailhog/mailhog

  clamav:
    image: dinkel/clamavd

  keycloak:
    depends_on:
      - db
      - mailhog
    image: acr.run/camac-ng/keycloak-uri/keycloak:11.0.2_theme-v0.3.2
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_USER=camac
      - DB_DATABASE=${APPLICATION}
      - DB_SCHEMA=keycloak
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true

volumes:
  pgdata:
  djangomedia:
  djangotmpmedia:
  phpsessions:
  templatefiles:
