version: "3.4"
services:
  proxy:
    restart: always
    depends_on:
      - iweb_mock
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/camac/nginx:/etc/nginx/conf.d:ro

  db:
    image: acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../db
      cache_from:
        - acr.run/camac-ng/camac-ng/db:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    volumes:
      - /etc/camac/postgres_password.conf:/run/secrets/postgres-passwd:ro

  django:
    image: acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../django
      cache_from:
        - acr.run/camac-ng/camac-ng/django:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    environment:
      - DJANGO_ENV_FILE=/run/secrets/django.env
    volumes:
      - /etc/camac/django.env:/run/secrets/django.env:ro

  php:
    image: acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../php
      cache_from:
        - acr.run/camac-ng/camac-ng/php:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    restart: always
    environment:
      - APPLICATION_ENV=production
    volumes:
      - /etc/camac/php.ini:/usr/local/etc/php/php.ini:ro
      - /etc/camac/application.ini:/var/www/camac/${APPLICATION}/configs/application.local.ini:ro
      # TODO: Implement resource fallback in document module, so this can be removed
      - phpresources:/var/www/camac/kt_uri/resources

  cache:
    restart: always

  clamav:
    restart: always

  mailhog:
    restart: always

  iweb_mock:
    image: acr.run/camac-ng/camac-ng/iweb_mock:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    build:
      context: ../iweb_mock
      cache_from:
        - acr.run/camac-ng/camac-ng/iweb_mock:${CI_COMMIT_REF_SLUG}-${APPLICATION}
    depends_on:
      - php
    environment:
      - NODE_ENV=stage

volumes:
  pgdata:
    external:
      name: camacpgdata

  djangomedia:
    external:
      name: camacdjangomedia

  phpsessions:
    external:
      name: camacphpsessions

  phpresources:
    external:
      name: camacphpresources
