[tool.black]
target-version = ["py36"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | .*/migrations
  | .*/echbern\/schema
  | .*/ech0211\/schema
  | .*/snapshots
)/
'''
